// <auto-generated />
using System;
using CipherAnnotation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CipherAnnotation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518233200_MakeSymbolImageOptional")]
    partial class MakeSymbolImageOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float>("Orientation")
                        .HasColumnType("real");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Transcription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("TranscriptionRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CaptionId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TranscriptionRefId");

                    b.HasIndex("PageId", "CaptionId", "CreatedAt");

                    b.ToTable("Annotations", t =>
                        {
                            t.HasCheckConstraint("CK_Annotation_TypeFields", "(\"Type\" = 'Text'   AND \"Transcription\" IS NULL AND \"TranscriptionRefId\" IS NULL AND \"SymbolId\" IS NULL) OR (\"Type\" = 'Cipher' AND \"TranscriptionRefId\" IS NULL AND \"SymbolId\" IS NULL) OR (\"Type\" = 'Symbol' AND \"Transcription\" IS NULL)");
                        });
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.BoundingBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnnotationId")
                        .HasColumnType("uuid");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationId")
                        .IsUnique();

                    b.ToTable("BoundingBoxes");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Caption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "CreatedAt");

                    b.HasIndex("DocumentId", "Name")
                        .IsUnique();

                    b.ToTable("Captions");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Visibility");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.DocumentShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SharedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DocumentId", "UserId")
                        .IsUnique();

                    b.ToTable("DocumentShares");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.FileBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.ToTable("FileBlobs");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CurrentPreprocessHistoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImageBlobId")
                        .HasColumnType("uuid");

                    b.Property<float>("Orientation")
                        .HasColumnType("real");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProcessedImageBlobId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResolutionDPI")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPreprocessHistoryId");

                    b.HasIndex("ImageBlobId");

                    b.HasIndex("ProcessedImageBlobId");

                    b.HasIndex("DocumentId", "PageNumber")
                        .IsUnique();

                    b.ToTable("Pages", t =>
                        {
                            t.HasCheckConstraint("CK_Page_PageNumber", "\"PageNumber\" >= 1 AND \"PageNumber\" <= 100");
                        });
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.PreprocessHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("OperationsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousBlobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultBlobId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResultHeight")
                        .HasColumnType("integer");

                    b.Property<int>("ResultWidth")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResultBlobId");

                    b.HasIndex("PageId", "Sequence")
                        .IsUnique();

                    b.ToTable("PreprocessHistoryEntries");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("ImageBlobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Content");

                    b.HasIndex("ImageBlobId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUri")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Annotation", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Caption", "Caption")
                        .WithMany("Annotations")
                        .HasForeignKey("CaptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.Page", "Page")
                        .WithMany("Annotations")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.Annotation", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CipherAnnotation.Core.Entities.Symbol", "Symbol")
                        .WithMany("Annotations")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CipherAnnotation.Core.Entities.Annotation", "TranscriptionRef")
                        .WithMany("ReferencedBy")
                        .HasForeignKey("TranscriptionRefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Caption");

                    b.Navigation("Page");

                    b.Navigation("Parent");

                    b.Navigation("Symbol");

                    b.Navigation("TranscriptionRef");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.BoundingBox", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Annotation", "Annotation")
                        .WithOne("BoundingBox")
                        .HasForeignKey("CipherAnnotation.Core.Entities.BoundingBox", "AnnotationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Annotation");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Caption", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Document", "Document")
                        .WithMany("Captions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Document", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.User", "Owner")
                        .WithMany("OwnedDocuments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.DocumentShare", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Document", "Document")
                        .WithMany("Shares")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.User", "User")
                        .WithMany("SharedDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Page", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.PreprocessHistoryEntry", null)
                        .WithMany()
                        .HasForeignKey("CurrentPreprocessHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CipherAnnotation.Core.Entities.Document", "Document")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "ImageBlob")
                        .WithMany()
                        .HasForeignKey("ImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "ProcessedImageBlob")
                        .WithMany()
                        .HasForeignKey("ProcessedImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("ImageBlob");

                    b.Navigation("ProcessedImageBlob");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.PreprocessHistoryEntry", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Page", "Page")
                        .WithMany("PreprocessHistory")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "ResultBlob")
                        .WithMany()
                        .HasForeignKey("ResultBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Page");

                    b.Navigation("ResultBlob");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Symbol", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "ImageBlob")
                        .WithMany()
                        .HasForeignKey("ImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CipherAnnotation.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageBlob");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Annotation", b =>
                {
                    b.Navigation("BoundingBox");

                    b.Navigation("Children");

                    b.Navigation("ReferencedBy");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Caption", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Document", b =>
                {
                    b.Navigation("Captions");

                    b.Navigation("Pages");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Page", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("PreprocessHistory");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Symbol", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.User", b =>
                {
                    b.Navigation("OwnedDocuments");

                    b.Navigation("SharedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
