// <auto-generated />
using System;
using CipherAnnotation.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CipherAnnotation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419181016_RemoveSymbolPHash")]
    partial class RemoveSymbolPHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CipherAnnotation.Core.Entities.BoundingBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<Guid?>("PairId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ElementId")
                        .IsUnique();

                    b.HasIndex("PairId")
                        .IsUnique();

                    b.HasIndex("SectionId")
                        .IsUnique();

                    b.ToTable("BoundingBoxes", t =>
                        {
                            t.HasCheckConstraint("CK_BoundingBox_SingleFK", "(CASE WHEN \"SectionId\" IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN \"PairId\" IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN \"ElementId\" IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 337, DateTimeKind.Utc).AddTicks(5520));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 337, DateTimeKind.Utc).AddTicks(5920));

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Visibility");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.DocumentShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SharedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 338, DateTimeKind.Utc).AddTicks(3800));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DocumentId", "UserId")
                        .IsUnique();

                    b.ToTable("DocumentShares");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.ElementAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 339, DateTimeKind.Utc).AddTicks(1530));

                    b.Property<float>("Orientation")
                        .HasColumnType("real");

                    b.Property<Guid>("PairId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("Transcription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PairId");

                    b.HasIndex("SymbolId");

                    b.ToTable("ElementAnnotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.FileBlob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 339, DateTimeKind.Utc).AddTicks(7160));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.ToTable("FileBlobs");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 337, DateTimeKind.Utc).AddTicks(9290));

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImageBlobId")
                        .HasColumnType("uuid");

                    b.Property<float>("Orientation")
                        .HasColumnType("real");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProcessedImageBlobId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResolutionDPI")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageBlobId");

                    b.HasIndex("ProcessedImageBlobId");

                    b.HasIndex("DocumentId", "PageNumber")
                        .IsUnique();

                    b.ToTable("Pages", t =>
                        {
                            t.HasCheckConstraint("CK_Page_PageNumber", "\"PageNumber\" >= 1 AND \"PageNumber\" <= 100");
                        });
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.PairAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 338, DateTimeKind.Utc).AddTicks(8590));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<float>("Orientation")
                        .HasColumnType("real");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("PairAnnotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.SectionAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 338, DateTimeKind.Utc).AddTicks(5700));

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Orientation")
                        .HasColumnType("real");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("SectionAnnotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Symbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 339, DateTimeKind.Utc).AddTicks(5810));

                    b.Property<Guid?>("PreviewImageBlobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PreviewImageBlobId");

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUri")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 19, 18, 10, 16, 337, DateTimeKind.Utc).AddTicks(1890));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.BoundingBox", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.ElementAnnotation", "Element")
                        .WithOne("BoundingBox")
                        .HasForeignKey("CipherAnnotation.Core.Entities.BoundingBox", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CipherAnnotation.Core.Entities.PairAnnotation", "Pair")
                        .WithOne("BoundingBox")
                        .HasForeignKey("CipherAnnotation.Core.Entities.BoundingBox", "PairId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CipherAnnotation.Core.Entities.SectionAnnotation", "Section")
                        .WithOne("BoundingBox")
                        .HasForeignKey("CipherAnnotation.Core.Entities.BoundingBox", "SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Element");

                    b.Navigation("Pair");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Document", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.User", "Owner")
                        .WithMany("OwnedDocuments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.DocumentShare", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Document", "Document")
                        .WithMany("Shares")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.User", "User")
                        .WithMany("SharedDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.ElementAnnotation", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.PairAnnotation", "Pair")
                        .WithMany("ElementAnnotations")
                        .HasForeignKey("PairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.Symbol", "Symbol")
                        .WithMany("Elements")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pair");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Page", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Document", "Document")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "ImageBlob")
                        .WithMany()
                        .HasForeignKey("ImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "ProcessedImageBlob")
                        .WithMany()
                        .HasForeignKey("ProcessedImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("ImageBlob");

                    b.Navigation("ProcessedImageBlob");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.PairAnnotation", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.SectionAnnotation", "Section")
                        .WithMany("PairAnnotations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.SectionAnnotation", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.Page", "Page")
                        .WithMany("SectionAnnotations")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Symbol", b =>
                {
                    b.HasOne("CipherAnnotation.Core.Entities.FileBlob", "PreviewImageBlob")
                        .WithMany()
                        .HasForeignKey("PreviewImageBlobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PreviewImageBlob");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Document", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.ElementAnnotation", b =>
                {
                    b.Navigation("BoundingBox");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Page", b =>
                {
                    b.Navigation("SectionAnnotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.PairAnnotation", b =>
                {
                    b.Navigation("BoundingBox");

                    b.Navigation("ElementAnnotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.SectionAnnotation", b =>
                {
                    b.Navigation("BoundingBox");

                    b.Navigation("PairAnnotations");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.Symbol", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("CipherAnnotation.Core.Entities.User", b =>
                {
                    b.Navigation("OwnedDocuments");

                    b.Navigation("SharedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
